spring:
  application:
    name: codari-user-local
  profiles:
    include: console-logging,oauth
  r2dbc:
    url: r2dbc:mariadb://122.43.41.113:53306/codari-user?useSSL=false
    username: codari-user
    password: codari
  jpa:
    database: mysql
    show-sql: true
    properties:
      hibernate:
        show-sql: true
        format-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    user: codari-user
    password: codari
    url: 'jdbc:mysql://122.43.41.113:53306/codari-user?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false'
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 3ca7b5b6af230388cc1c04e985bd4128
            client-secret: QzUA5LZYjfWeGVjNu3FtS5CVyviaYZKg
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile_nickname
              - profile_image
              - account_email
        provider:
          kakao:
            authorization-uri: 'https://kauth.kakao.com/oauth/authorize'
            token-uri: 'https://kauth.kakao.com/oauth/token'
            user-info-uri: 'https://kapi.kakao.com/v2/user/me'
            user-name-attribute: id

app-security:
  oauth2:
    authorizedRedirectUris:
      - 'http://localhost:8080/oauth2/redirect'