logging:
  config: classpath:logback-spring.xml
  level:
    root: info
spring:
  application:
    name: codari-user
  config:
    use-legacy-processing: true
  main.allow-bean-definition-overriding: true
  r2dbc:
    url: r2dbc:mariadb://localhost:3306/codari-user?useSSL=false
    username: codari-user
    password: codari
    pool:
      initial-size: 100
      max-size: 500
      max-idle-time: 30m
      validation-query: SELECT 1
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    show-sql: false
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        show-sql: false
        format-sql: false
        use-sql-comments: false
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 3ca7b5b6af230388cc1c04e985bd4128
            client-secret: QzUA5LZYjfWeGVjNu3FtS5CVyviaYZKg
            redirect-uri: 'http://3.38.36.193/login/oauth2/code/kakao'
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile_nickname
              - profile_image
              - account_email
        provider:
          kakao:
            authorization-uri: 'https://kauth.kakao.com/oauth/authorize'
            token-uri: 'https://kauth.kakao.com/oauth/token'
            user-info-uri: 'https://kapi.kakao.com/v2/user/me'
            user-name-attribute: id


app-security:
  auth:
    tokenSecret: CODARI-SECRET #JWT Secret Key
    tokenExpirationMsec: 864000000